### ISSUE TITLE
Missing user_id logging - undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by matteodesimone** [datariot/omniauth-paypal#11]
Hi!
I'm authenticating by paypal (both sendbox and live).

After Paypal authentication my app redirect to /users/auth/paypal/callback
and raise a undefined method `[]' for nil:NilClass error on  lib/omniauth/strategies/paypal.rb:

```
uid { @parsed_uid ||= (/\/([^\/]+)\z/.match raw_info['user_id'])[1] } #https://www.paypal.com/webapps/auth/identity/user/baCNqjGvIxzlbvDCSsfhN3IrQDtQtsVr79AwAjMxekw => baCNqjGvIxzlbvDCSsfhN3IrQDtQtsVr79AwAjMxekw
```

I checked the content of raw_info and there isn't any "user_id" element inside:

--- family_name: Joe language: en_US locale: en_US zoneinfo: America/Los_Angeles name: Seller Joe birthday: '1982-08-02' given_name: Seller

Do you think this could be a omniauth-paypal bug?

Thank you for any hint to face this situation.

I'm working on Ruby 2.0.0 and Rails 4.0.0.

This is the trace:

```
omniauth-paypal (1.1) lib/omniauth/strategies/paypal.rb:23:in `block in <class:PayPal>'
omniauth (1.1.4) lib/omniauth/strategy.rb:106:in `instance_eval'
omniauth (1.1.4) lib/omniauth/strategy.rb:106:in `block in compile_stack'
omniauth (1.1.4) lib/omniauth/strategy.rb:105:in `each'
omniauth (1.1.4) lib/omniauth/strategy.rb:105:in `inject'
omniauth (1.1.4) lib/omniauth/strategy.rb:105:in `compile_stack' (eval):7:in `uid_stack'
omniauth (1.1.4) lib/omniauth/strategy.rb:318:in `uid'
omniauth (1.1.4) lib/omniauth/strategy.rb:334:in `auth_hash'
omniauth (1.1.4) lib/omniauth/strategy.rb:362:in `callback_phase'
omniauth-oauth2 (1.1.1) lib/omniauth/strategies/oauth2.rb:77:in `callback_phase'
omniauth (1.1.4) lib/omniauth/strategy.rb:226:in `callback_call'
omniauth (1.1.4) lib/omniauth/strategy.rb:182:in `call!'
omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.1.4) lib/omniauth/builder.rb:49:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.0) lib/active_record/migration.rb:369:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__1072537632891380873__call__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
railties (4.0.0) lib/rails/engine.rb:511:in `call'
railties (4.0.0) lib/rails/application.rb:97:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
```

Request dump

```
Parameters:

{"state"=>"8bfe5cffd8d26a6b23c6d282b475481d7dfba90479e56203",
 "scope"=>"profile",
 "code"=>"NtcwjeZ6LXkp8ve61z8vEWemGcuc2Bt4DHV905hs5ysQfGtPuXclQD4iHSNCDOO15xCR0MG99fvO0SJg8Dh1lfoObMMVkH9SmD8hlcjdusQPEl_fjnCoGRQ-vw2yHPBlfB4WP8-u02Ap2tXSSAkzoju_sUgBQHV4rcjptmr1L1qyQCrs"}
```

Session dump

```
_csrf_token: "3El2TXYzW4aRd+trRniEt0/ubZeXfEoEHQbMcp2mOiQ="
omniauth.state: "8bfe5cffd8d26a6b23c6d282b475481d7dfba90479e56203"
session_id: "5f83792a42a181d3ff0a77eecf1e523e"
```

Env dump

```
GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "it-it"
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "127.0.0.1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"
```

This is my Gem list:

```
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
group :doc do
  gem 'sdoc', require: false
end
gem 'cancan'
gem 'devise', '~>3.0.3'
gem "omniauth"
gem "omniauth-paypal"
```

My omniauth initializer

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :paypal, PAYPAL_CONFIG['app_id'], PAYPAL_CONFIG['app_token'], sandbox: true if not Rails.env.production?
  provider :paypal, PAYPAL_CONFIG['app_id'], PAYPAL_CONFIG['app_token'], sandbox: false if Rails.env.production? 
end
```
